server:
  port: 8080

spring:
  application:
    name: triage-agent
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        max.block.ms: 5000
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    mcp:
      client:
        toolcallback:
          enabled: true
        sse:
          connections:
            grafana:
              url: http://mcp-grafana:8000
            jaeger:
              url: http://jaeger-mcp-service:8080